GET  http://localhost:5000/information

###

GET  http://localhost:5000/information/5d55a47ee42ec839bcde3927

###

POST http://localhost:5000/information
Content-Type: application/json

{
    "name": "Spring Race 10km",
    "distance": 10,
    "date": "2019-04-12 15:00",
    "capacity": 100,
    "location": "Malmö",
    "message": "Welcome to the Spring Race 10km in Gothenburg! Good luck!"
}

###

DELETE http://localhost:5000/information/5d55a9128220bd2a3052e375

###

PATCH http://localhost:5000/information/5d55a92d8220bd2a3052e376
Content-Type: application/json

{
    "name": "Sommarloppet"
}